string_u8_litexpr( "c8"  ), finalize_color( defcolor_keyword, 0 ), 
string_u8_litexpr( "u8"  ), finalize_color( defcolor_keyword, 0 ), 
string_u8_litexpr( "u16" ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "u32" ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "u64" ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "s8"  ), finalize_color( defcolor_keyword, 0 ), 
string_u8_litexpr( "s16" ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "s32" ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "s64" ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "r32" ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "r64" ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "v2"  ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "v3"  ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "v4"  ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "m2"  ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "m3"  ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "m4"  ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "b32" ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "midx"), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "umm" ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "smm" ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "bptr" ), finalize_color( defcolor_keyword, 0 ),
string_u8_litexpr( "__debugbreak" ), 0xffa46391, /* Hardcoded colors work too. */